import type { Metadata } from 'next';
import { Open_Sans, Fira_Code } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar';
import AnimatedBackground from '@/components/animatedBg';
import Container from '@/components/container';
import Footer from '@/components/footer';
import { ThemeProvider } from '@/components/theme-provider';

const openSans = Open_Sans({
  variable: '--font-sans',
  subsets: ['latin'],
});

const firaCode = Fira_Code({
  variable: '--font-code',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Dev Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${openSans.variable} ${firaCode.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AnimatedBackground />
          <Navbar />
          <Container>{children}</Container>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
