import type { Metadata } from 'next';
import { Open_Sans, Fira_Code } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar';
import AnimatedBackground from '@/components/animatedBg';
import Container from '@/components/container';
import Footer from '@/components/footer';

const openSans = Open_Sans({
  variable: '--font-open-sans',
  subsets: ['latin'],
});

const firaCode = Fira_Code({
  variable: '--font-fira-code',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} ${firaCode.variable} antialiased`}>
        <AnimatedBackground />
        <Navbar />
        <Container>{children}</Container>
        <Footer />
      </body>
    </html>
  );
}
