import type { Metadata } from "next";
import { Open_Sans, Fira_Code } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Container from "@/components/container";
import Footer from "@/components/footer";
import { ThemeProvider } from "@/components/theme-provider";
import ConstellationBackground from "@/components/animation/animated-bg";
import LoadingWrapper from "@/components/animation/loader-wrapper";
import SimpleConstellationLoader from "@/components/animation/loader";

const openSans = Open_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  variable: "--font-code",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "nsch.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${openSans.variable} ${firaCode.variable} antialiased text-base md:text-sm`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <LoadingWrapper
            loader={<SimpleConstellationLoader />}
            duration={2900}
          >
            <ConstellationBackground />
            <Navbar />
            <Container>{children}</Container>
            <Footer />
          </LoadingWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
